name: Publish to Docker
on:
  push:
    branches:
      - main
  permissions:
    packages: write
  jobs:
    publish:
      run-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Build container
           uses: docker/build-push-action@v1
           with:
             username: Rohit-rg
             password: ${{ secrets.GITHUB_TOKEN }}
             registry: docker.pkg.github.com
             repository: Rohit-rg/publish-packages/game
             tag_with_sha: true 
